### ISSUE TITLE
test(types): install runtime dependencies in the built consumer fixture

### ISSUE THREAD

**Issue by chrisbbreuer** [stacksjs/stacks#2523]
The package-consumer regression introduced in #2518 passes on the developer checkout but fails in clean Linux CI: `Cannot find module @stacksjs/strings` from the built types root. The test builds and copies `@stacksjs/types` but leaves its declared strings dependency to workspace fallback; local `strings/dist` masks the gap.

Authoritative failure: https://github.com/stacksjs/stacks/actions/runs/34280479753/job/102243749162 at 1454f393f1, Bun 1.4.2 / Linux x64. This is the only failing core package in that run.

Fix the fixture to build and install the real strings dependency with the real package build, assert both package resolutions stay inside the fixture, and exercise the root helper that imports strings. Do not add source aliases, stub the dependency, skip the consumer, weaken enum identity assertions, or build dependencies implicitly in unrelated jobs. Verify local checks and a fresh CI run.

**Comment by chrisbbreuer** [comment]
Pushed [5a48028ded](https://github.com/stacksjs/stacks/commit/5a48028ded) to `main`. The consumer fixture now builds and installs the real strings and types packages, verifies fixture-local resolution, and exercises the string-backed helper while retaining enum identity and value checks.

The new resolution assertion failed before the fixture change and passed after it. Validation: 327 relevant framework tests plus 409 application tests passed; framework typechecking and Pickier lint passed; independent standards and specification reviews passed. Fresh Linux CI confirmation remains pending. This repairs the validation gap from #2518; it makes no performance claim. The separate dashboard typecheck failure is tracked in #2524.

**Comment by chrisbbreuer** [comment]
Fresh Linux CI confirmed the fixture fix: the [test job for 5a48028ded](https://github.com/stacksjs/stacks/actions/runs/34282697112/job/102250989244) passed. The overall run is still red solely because of the separate dashboard typecheck failure tracked in #2524.
