### ISSUE TITLE
test: 29 core tests fail together and pass in isolation, so the suite cannot be read as a signal

### ISSUE THREAD

**Issue by chrisbbreuer** [stacksjs/stacks#2413]
29 tests fail when the whole `storage/framework/core/` tree runs in one process, and pass when their own file runs alone. Found while verifying #2411; the count is identical before and after that change, so it is pre-existing rather than caused by it.

```
$ bun test ./storage/framework/core/actions/tests/make-job.test.ts
 14 pass, 0 fail

$ bun test ./storage/framework/core/
 (fail) makeJob > job creation > should create a function-based job file
 (fail) makeJob > job creation > should append Job suffix if not present
 (fail) makeCommand > command creation > should create a command file
 ... 29 total
```

The visible ones are the `make:*` scaffolding suites, which write real files into `app/Jobs/`, `app/Commands/` and friends and then assert on them. Run beside other suites that touch the same paths, they interfere.

## Why it matters more than the failures themselves

**It makes the suite unusable as a signal.** Verifying a change means comparing failure counts before and after and hoping the same 29 fail both times, rather than reading green as green. That is a slow, error-prone check, and it is exactly the situation where a real regression hides inside accepted noise.

It also means `bun test ./storage/framework/core/` cannot be wired into CI as-is, so nothing currently catches a cross-suite regression.

## Related debris

The `make-stack` suite leaves a `test-make-stack-basic/` directory in the repository root - `app/`, `config/` and more - after a full-tree run. Untracked, so it shows up as noise in `git status` and could be committed by accident with a broad `git add`.

## Shape of a fix

Each scaffolding test wants its own temp directory rather than the real project tree, the way the ORM schema tests already do (`mkdtempSync` + a scoped `projectPath`). That is the difference between suites that pass in isolation and suites that pass together.

Worth checking whether the remaining failures beyond `make:*` share the same cause or are a second, independent one - I did not enumerate all 29.

**Comment by chrisbbreuer** [comment]
Fixed in `ebe8b269f6`. **All 29 pass together now.** CI green.

Three files mutated process-global state and never put it back. Bun rolls none of it back between test files, so whatever they left behind is what every later file inherited.

## One mock caused fifteen of them

`payments/tests/stripe-setup-idempotency.test.ts` mocked `@stacksjs/logging` with a `log` of **four** methods where the real one has **sixteen**, and `@stacksjs/config` with a single key:

```ts
mock.module('@stacksjs/logging', () => ({ log: { debug() {}, error() {}, info() {}, warn() {} } }))
mock.module('@stacksjs/config', () => ({ saas: { plans } }))
```

Every file after it imported those. `log.success` was not a function, which is the whole of: `ensureDeployEnvIsSet` (7), `makeJob` (3), `makeCommand` (3), `setup IDE settings` (1), `buildLibraryPackages` (1). Both mocks now spread the module they stand in for.

`subscription-is-valid.test.ts` replaced `db` and never restored it, so ten later tests got `db.unsafe is not a function`. Restored in `afterAll`, captured with a spread for the reason `core/testing` already documents in its own comment: mocking patches the live namespace in place, so a bare capture would restore the mock itself.

## One was not cross-suite at all

`env/test/active-env-name.test.ts` failed **on its own** - 2 pass, 3 fail. It cleared `NODE_ENV`, `APP_ENV` and `DOTENV_ENV`, but `activeEnvName()` reads `loadedEnvName` ahead of all three, and that is module state the preload had already set to `test`. The test was asserting on an input it did not control. `resetPrivateKeyCache()` exists for exactly this (added in #2259) and it now calls it.

`config/tests/overrides-shape.test.ts` compared a snapshot taken when config first loaded against `process.env` at assertion time; twelve files set `APP_ENV = 'testing'` at module scope for their database setup, so the two disagreed. It exercises `defaultsForOverrides()` directly now, which pins the rule without depending on load order.

## Two production bugs it surfaced

Both were reachable outside tests, and both are worth more than the failures that led to them.

**`utils/src/observer.ts` could overflow the stack.** `rafId` is assigned only *after* `raf(...)` returns, so a `requestAnimationFrame` that invokes its callback synchronously - a polyfill, a non-browser host, or the test double that was leaking out of `use-auth-refresh.test.ts` - reaches the re-entry guard while `rafId` is still null and recurses until the stack blows. It took the whole process down, which is why the runner never printed a summary. Guarded with a flag armed for the duration of `raf(...)`.

**`scheduler/src/schedule.ts` emitted unparseable scripts.** A background task runs by having its source evaluated in a new process. A native or bound function stringifies to `function () { [native code] }`, so the child died on a parse error that arrived on the parent's stderr with no task name attached. Refused up front now, with a message naming the task and the fix.

## Still open, and it is the reason this issue was worth filing

`bun test ./storage/framework/core/` still exits 1 and prints **no summary** - before and after this change alike. Zero tests report failure; the actions suite simply ends immediately after writing into the real `app/Commands/`. So the suite is readable now in the sense that nothing fails spuriously, but it still cannot be wired into CI as a green/red signal until that early termination is understood. That is a separate bug and wants its own pass; I have not chased it.

The `make-stack` suite also still leaves `test-make-stack-basic/` in the repository root.

Verified per suite: config 183, env 243, payments 167, utils 190, browser 104, scheduler 154, buddy 631 - all green. Lint clean, both typechecks clean.

**Comment by chrisbbreuer** [comment]
`bun test ./storage/framework/core/` **now finishes.** `ce4e1673e8`, CI green.

```
before today   never completed - no summary, no count
after          11773 tests, 815 files, 75s, 11761 pass, 12 fail
```

## Why it never finished

Six fixtures acquired the database config lock at module scope and released it from a `process.on('exit')` handler. Every test file shares one process, so "until exit" meant "for the rest of the run". Each of the 26 files that wants the lock then waited out the full 60s watchdog before it could start.

Six holders, twenty-six waiters. The run spent longer stalled than working and was routinely killed before reaching the end - which is exactly why this suite had no summary and no usable failure count, and why the deeper failures in it had never been seen by anyone.

The lock now wraps `forceConfig()`, the one function that mutates the shared config, in a try/finally. **Nothing is given up by narrowing it:** the watchdog was already force-releasing after 60s, so the old code never actually held the lock to the end - it just made everything else pay a minute to find that out. The DB *file* cleanup stays on `process.on('exit')`, where it does belong, since the shared sqlite file has to outlive the last importing file.

## A regression of mine, fixed in the same commit

`ebe8b269f6` made the payments mocks faithful in **shape** - spreading the module so `log.success` exists - but left them installed for the rest of the run. A silenced `log` is the one thing `core/logging`'s suite must not be handed, since it asserts on what gets emitted: **54 of its tests failed.** Shape and lifetime are separate problems and I had only fixed the first. The mocks are restored in `afterAll` now, captures spread so restoring cannot hand back the patched namespace.

That also corrects my earlier comment here. I reported "all 29 pass together now" off a run that terminated early - with the run dying partway, a lower failure count meant fewer files reached, not more tests passing. The number was not comparable to the 29, and I should have noticed the file count had dropped rather than treating zero as a result.

## What is left

**12 failures**, all in `core/email`, which passes alone and after `core/logging`. Plus 6 in `core/logging` that depend on which file ran before it - one `log.info` lands 2-3 records in a fresh sink, so a transport from an earlier file is still attached. Both are pre-existing and neither was reachable from a run that does not finish.

The failure set is now **byte-identical between runs**, so the suite can finally be read as a signal rather than a count to compare against last time.

## Separately: a flaky CI job

`deployment-target` failed on this commit with `RangeError: Maximum call stack size exceeded`, thrown *after* `resolve-target.ts` had already printed its correct result - so it overflows during teardown, and the step still exits 1. Re-running the same job on the same commit passed. Worth its own look, since a flake that only shows up after the work succeeded will be hard to catch later.

**Comment by chrisbbreuer** [comment]
`9288d0f3a0`, CI green. **11773 tests, 815 files, ~85s, 11770 passing.**

```
before today   never completed - no summary, no count
after the lock fix   11761 pass, 12 fail
now                  11770 pass,  3 fail
```

## The email twelve

`auth/tests/magic-link.test.ts` mocked `@stacksjs/email` and never restored it, so every later file got a `mail` with two methods and a `template` returning empty strings. Its three sibling files that mock the same module all restore it; this one was the exception.

The last one was more interesting. `email/src/template.ts` cached the generated template registry once per process - but every path in it comes from `storagePath()`, which walks up from `process.cwd()`. **The cache was only ever valid for the directory it was built in.** `core/email`'s template-resolution suite chdirs into a temp project, so any earlier file that resolved a template left the registry answering with the real repo's paths, and the userland override under the temp root was never seen. Keyed on its cwd now. `resetTemplateRegistry()` remains the explicit way to drop it; no caller has to know to.

## The logging six could not have passed reliably

Those tests asserted an exact record count against a sink that captured *everything*. In a single-process run the framework logs from background work - `[orm] Defining model: ...` lands mid-assertion, from model loading a previous suite started - so `toHaveLength(1)` passed or failed on which file ran before it, not on anything the suite controls. Worth stating plainly: this was not a test that broke, it was a test that could never have been trustworthy. The sink ignores records from other subsystems now, and every assertion stays exactly as strict about what the suite itself logs.

## What is left, and why I stopped

Two failures, both `core/email` hitting a **closed sqlite handle** left behind by `core/database`. Filed as #2415 with the bisection: it reproduces from a group of 8 files and **from no single one of them**, so it is an interaction between files, and `resetDatabaseConnection()` already exists for exactly that state.

I could have made both green in one line by extending `getSuppressions`' existing "cannot check" path to cover a closed handle. I did not: that path silently stops enforcing suppression, and widening a safety control's failure-open case to clear a red suite is a product decision, not a test fix.

One more, `throttle > should handle zero wait time`, is timing-based - it failed in one full run and passed in the next on the same commit.

**Comment by chrisbbreuer** [comment]
Done. `bun test ./storage/framework/core/` is **11867 pass, 0 fail** in ~84s, deterministic across runs.

The title asked for a suite that can be read as a signal. It now can.

What it took, in order of how much each mattered:

- **The db config lock** (`ce4e1673e8`) - six fixtures held a process-wide lock until `process.exit`, so each of 26 files that wanted it burned the full 60s watchdog. This is why the run never finished at all; everything below was invisible behind it.
- **A connection closed under a live builder** (`8bc27ddf6e`, upstream `bun-query-builder@0.2.62`) - 115 `Cannot use a closed database` errors from one library call closing a cached connection other callers still held.
- **Module mocks never restored** (`ebe8b269f6`) - one file mocking `@stacksjs/logging` with 4 of its 16 methods cost 15 unrelated tests across five packages.
- **An unhandled error with no test attached** (`d7ba433790`) - `resolveApiBaseUrl` reading `window.location` off a harness `window`. Counted in the summary, absent from `--reporter=junit`, invisible to every per-package scan.
- Plus a stack overflow in `utils/observer.ts` and an unparseable background-task script in `scheduler`, both real production bugs the isolation work surfaced.

Two things worth carrying forward:

**Never compare failure counts from a truncated run.** I reported "29 → 0" off a run that had died partway; fewer files reached looks exactly like fewer failures. Check the `Ran N tests across M files` line before believing any count.

**`bun test <dir>` and `bun test <the same files listed>` are not equivalent.** Same 820 files, wildly different results - the directory form's discovery order is not sorted, and only that order reproduced the connection bug. Passing them in `find` order is what made bisection possible.
